local ConfigBigMap = {
               [1] = {
                       sizeX = 1024,
                       sizeY = 1024,
                       posX = -128,
                       posY = 1978,
                       part = "UpLeft",
                       image = "1",
                    },
               [2] = {
                       sizeX = 1024,
                       sizeY = 1024,
                       posX = 896,
                       posY = 1978,
                       part = "Up",
                       image = "2",
                    },
               [3] = {
                       sizeX = 1024,
                       sizeY = 1024,
                       posX = 1920,
                       posY = 1978,
                       part = "Up",
                       image = "3",
                    },
               [4] = {
                       sizeX = 1024,
                       sizeY = 1024,
                       posX = 2944,
                       posY = 1978,
                       part = "Up",
                       image = "4",
                    },
               [5] = {
                       sizeX = 604,
                       sizeY = 1024,
                       posX = 3758,
                       posY = 1978,
                       part = "UpRight",
                       image = "5",
                    },
               [6] = {
                       sizeX = 1024,
                       sizeY = 1024,
                       posX = -128,
                       posY = 954,
                       part = "Left",
                       image = "6",
                    },
               [7] = {
                       sizeX = 1024,
                       sizeY = 1024,
                       posX = 896,
                       posY = 954,
                       part = "Middle",
                       image = "7",
                    },
               [8] = {
                       sizeX = 1024,
                       sizeY = 1024,
                       posX = 1920,
                       posY = 954,
                       part = "Middle",
                       image = "8",
                    },
               [9] = {
                       sizeX = 1024,
                       sizeY = 1024,
                       posX = 2944,
                       posY = 954,
                       part = "Middle",
                       image = "9",
                    },
               [10] = {
                       sizeX = 604,
                       sizeY = 1024,
                       posX = 3758,
                       posY = 954,
                       part = "Right",
                       image = "10",
                    },
               [11] = {
                       sizeX = 1024,
                       sizeY = 802,
                       posX = -128,
                       posY = 41,
                       part = "DownLeft",
                       image = "11",
                    },
               [12] = {
                       sizeX = 1024,
                       sizeY = 802,
                       posX = 896,
                       posY = 41,
                       part = "Down",
                       image = "12",
                    },
               [13] = {
                       sizeX = 1024,
                       sizeY = 802,
                       posX = 1920,
                       posY = 41,
                       part = "Down",
                       image = "13",
                    },
               [14] = {
                       sizeX = 1024,
                       sizeY = 802,
                       posX = 2944,
                       posY = 41,
                       part = "Down",
                       image = "14",
                    },
               [15] = {
                       sizeX = 604,
                       sizeY = 802,
                       posX = 3758,
                       posY = 41,
                       part = "DownRight",
                       image = "15",
                    },
             }
 return ConfigBigMap